*** Settings ***
Documentation    Generated by    _gherkin2robotframework on 2021-04-14T17:35:23.876172_
Library    Collections
Library    SeleniumLibrary

*** Keywords ***
I launch chrome browser
    Open Browser  https://www.google.com  chrome

I enter the URL
    Go To  https://www.github.com

I should see the home screen
    Title Should Be  GitHub: Where the world builds software · GitHub

